const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");
const { getModel } = require("../../models/LlmModel");


module.exports.pdfAgent = async (state) => {
    try {
        const llm = getModel("pdf");
        const response = await llm.invoke(`
Create a professional document about:

${state.prompt}

Rules:

- Professional title
- Introduction
- Multiple sections
- Bullet points where appropriate
- Conclusion

Return plain text only.

No markdown.
No code blocks.
`);

        const text = response.content.trim();
        const lines = text.split("\n").filter(Boolean);

        const title = lines[0]?.length < 100 ? lines[0] : state.prompt;
        const cleanText = text.replace(/```/g, "").replace(/\*\*/g, "").replace(/#/g, "");
        const filename = `pdf-${Date.now()}.pdf`;
        const outputPath = path.join(__dirname, "../../public/generated", filename);

        const doc = new PDFDocument({ size: "A4", margin: 50 });
        const stream = fs.createWriteStream(outputPath);
        doc.pipe(stream);
        doc.fontSize(24).text(title, { align: "center" });
        doc.moveDown();
        doc.fontSize(10).fillColor("gray").text(`Generated by KryptAI • ${new Date().toLocaleString()}`, { align: "center" });
        doc.moveDown(2);
        doc.fontSize(12).fillColor("black").text(cleanText, { lineGap: 5 });
        doc.end();

        await new Promise((resolve) => {
            stream.on("finish", resolve);
        });

        const pdfUrl = `${process.env.BACKEND_URL}/generated/${filename}`;
        return {...state,
            aiResponse: `# 📄 PDF Generated
Your PDF has been created successfully.

[Download PDF](${pdfUrl})
`,
        };
    } catch(err) {
        console.log(err);
        return { ...state, aiResponse: "❌ Failed to generate PDF." }
    }
};