const pptxgen = require("pptxgenjs");
const path = require("path");
const { getModel } = require("../../models/LlmModel");


const THEME = { dark: "0F172A", primary: "2563EB", white: "FFFFFF", offWhite: "F8FAFC", text: "1E293B", muted: "64748B", card: "EFF6FF" };

function addCoverSlide(ppt, title, subtitle) {
    const slide = ppt.addSlide();
    slide.background = { color: THEME.dark };

    slide.addShape(ppt.ShapeType.ellipse, {
        x: 10.5,
        y: -1.2,
        w: 4,
        h: 4,
        fill: { color: THEME.primary, transparency: 75 },
        line: { color: THEME.primary, transparency: 75 },
    });

    slide.addShape(ppt.ShapeType.ellipse, {
        x: -0.8,
        y: 5.5,
        w: 2.5,
        h: 2.5,
        fill: { color: THEME.primary, transparency: 80 },
        line: { color: THEME.primary, transparency: 80 },
    });

    slide.addText(title, {
        x: 0.7,
        y: 2,
        w: 11.9,
        h: 1.2,
        fontSize: 36,
        bold: true,
        color: THEME.white,
        fontFace: "Calibri",
        align: "center",
    });

    if (subtitle) {
        slide.addText(subtitle, {
            x: 0.7,
            y: 3.4,
            w: 11.9,
            h: 0.5,
            fontSize: 16,
            color: "94A3B8",
            fontFace: "Calibri",
            align: "center",
        });
    }

    slide.addText("Generated by KryptAI", {
        x: 0.7,
        y: 6.7,
        w: 11.9,
        h: 0.25,
        fontSize: 10,
        color: "475569",
        fontFace: "Calibri",
        align: "center",
    });
}


function addBulletSlide(ppt, slideIndex, title, bullets) {
    const slide = ppt.addSlide();
    slide.background = { color: THEME.white };

    slide.addShape(ppt.ShapeType.ellipse, {
        x: 12.5, y: 0.15, w: 0.45, h: 0.45,
        fill: { color: THEME.primary },
        line: { color: THEME.primary },
    });
    slide.addText(`${slideIndex}`, {
        x: 12.5, y: 0.15, w: 0.45, h: 0.45,
        fontSize: 10, bold: true, color: THEME.white,
        fontFace: "Calibri", align: "center", valign: "middle",
    });
    slide.addText(title, {
        x: 0.6, y: 0.25, w: 11.6, h: 0.65,
        fontSize: 28, bold: true, color: THEME.primary,
        fontFace: "Calibri",
    });
    slide.addShape(ppt.ShapeType.line, {
        x: 0.6, y: 0.95, w: 11.8, h: 0,
        line: { color: "CBD5E1", width: 1.5 },
    });

    const cardH = 0.72;
    const startY = 1.15;
    const gap = 0.12;

    bullets.slice(0, 6).forEach((txt, i) => {
        const y = startY + i * (cardH + gap);

        slide.addShape(ppt.ShapeType.roundRect, {
            x: 0.6, y, w: 11.8, h: cardH,
            fill: { color: i % 2 === 0 ? THEME.card : THEME.offWhite },
            line: { color: "DBEAFE" },
            rectRadius: 0.08,
        });
        slide.addShape(ppt.ShapeType.ellipse, {
            x: 0.85, y: y + 0.24, w: 0.22, h: 0.22,
            fill: { color: THEME.primary },
            line: { color: THEME.primary },
        });
        slide.addText(txt, {
            x: 1.2, y: y + 0.1, w: 10.9, h: cardH - 0.2,
            fontSize: 14, color: THEME.text,
            fontFace: "Calibri", valign: "middle",
        });
    });
    slide.addText("KryptAI", {
        x: 0.6, y: 7.0, w: 2, h: 0.2,
        fontSize: 9, color: THEME.muted, fontFace: "Calibri",
    });
}


function addStatSlide(ppt, slideIndex, title, stats) {
    const slide = ppt.addSlide();
    slide.background = { color: THEME.dark };

    slide.addText(title, {
        x: 0.6, y: 0.3, w: 12, h: 0.65,
        fontSize: 28, bold: true, color: THEME.white,
        fontFace: "Calibri",
    });
    slide.addShape(ppt.ShapeType.line, {
        x: 0.6, y: 1.0, w: 11.8, h: 0,
        line: { color: THEME.primary, width: 2 },
    });

    const cols = stats.length <= 3 ? stats.length : 4;
    const cardW = 11.8 / cols;
    const startX = 0.6;

    stats.slice(0, 4).forEach((s, i) => {
        const x = startX + i * cardW;
        slide.addShape(ppt.ShapeType.roundRect, {
            x: x + 0.1, y: 1.5, w: cardW - 0.2, h: 3.8,
            fill: { color: "1E3A5F" },
            line: { color: THEME.primary, width: 1 },
            rectRadius: 0.12,
        });
        slide.addText(s.value, {
            x: x + 0.1, y: 1.9, w: cardW - 0.2, h: 1.5,
            fontSize: 40, bold: true, color: THEME.primary,
            fontFace: "Calibri", align: "center",
        });
        slide.addText(s.label, {
            x: x + 0.1, y: 3.5, w: cardW - 0.2, h: 1.4,
            fontSize: 14, color: "CBD5E1",
            fontFace: "Calibri", align: "center",
        });
    });

    slide.addText("KryptAI", {
        x: 0.6, y: 7.0, w: 2, h: 0.2,
        fontSize: 9, color: THEME.muted, fontFace: "Calibri",
    });
}


function addConclusionSlide(ppt, title, points) {
    const slide = ppt.addSlide();
    slide.background = { color: THEME.primary };

    slide.addShape(ppt.ShapeType.ellipse, {
        x: 10, y: 4.5, w: 5, h: 5,
        fill: { color: "1D4ED8", transparency: 60 },
        line: { color: "1D4ED8", transparency: 60 },
    });
    slide.addText(title, {
        x: 0.7, y: 1.0, w: 9, h: 0.9,
        fontSize: 34, bold: true, color: THEME.white,
        fontFace: "Calibri",
    });
    slide.addText("Key Takeaways", {
        x: 0.7, y: 2.1, w: 9, h: 0.4,
        fontSize: 14, color: "BFDBFE",
        fontFace: "Calibri",
    });

    points.slice(0, 4).forEach((p, i) => {
        slide.addShape(ppt.ShapeType.ellipse, {
            x: 0.7, y: 2.7 + i * 0.75, w: 0.3, h: 0.3,
            fill: { color: THEME.white },
            line: { color: THEME.white },
        });
        slide.addText(p, {
            x: 1.2, y: 2.65 + i * 0.75, w: 8.5, h: 0.55,
            fontSize: 15, color: THEME.white,
            fontFace: "Calibri",
        });
    });

    slide.addText("Generated by KryptAI", {
        x: 0.7, y: 7.0, w: 11.9, h: 0.2,
        fontSize: 9, color: "BFDBFE",
        fontFace: "Calibri", align: "center",
    });
}


function parseResponse(content) {
    const result = { title: "", subtitle: "", slides: [] };
    const titleMatch = content.match(/^TITLE:\s*(.+)/m);
    result.title = titleMatch?.[1]?.trim() || "Presentation";
    const subtitleMatch = content.match(/^SUBTITLE:\s*(.+)/m);
    result.subtitle = subtitleMatch?.[1]?.trim() || "";
    const rawSlides = content.split(/^SLIDE:/m).slice(1);

    rawSlides.forEach((raw) => {
        const lines = raw.split("\n").map((l) => l.trim()).filter(Boolean);
        const titleLine = lines.find((l) => l.startsWith("Title:"));
        const typeLine = lines.find((l) => l.startsWith("Type:"));
        const title = titleLine?.replace("Title:", "").trim() || "Slide";
        const type = typeLine?.replace("Type:", "").trim().toLowerCase() || "bullets";
        const items = lines.filter((l) => l.startsWith("- ")).map((l) => l.replace(/^-\s*/, "").trim());
        const stats = items.map((item) => {
            const parts = item.split("|").map((p) => p.trim());
            return parts.length === 2
                ? { label: parts[0], value: parts[1] }
                : { label: item, value: "" };
        });

        result.slides.push({ title, type, items, stats });
    });

    return result;
}


module.exports.pptAgent = async (state) => {
    try {
        const llm = getModel("ppt");
        const aiResponse = await llm.invoke(`
Create a professional PowerPoint presentation on the topic below.

Topic:
${state.prompt}

Output Rules:

- No markdown.
- No explanation.
- Return ONLY the format below.
- Generate exactly 8 content slides.
- Slide types:
    • bullets
    • stats (use once)
    • conclusion (last slide)

Format:

TITLE: Presentation Title

SUBTITLE: One line subtitle

SLIDE:
Type: bullets
Title: Introduction
- Point
- Point
- Point
- Point

SLIDE:
Type: stats
Title: Key Numbers
- Users | 10M+
- Revenue | 42%
- Countries | 35

SLIDE:
Type: conclusion
Title: Conclusion
- Takeaway
- Takeaway
- Takeaway
`);

        const parsed = parseResponse(aiResponse.content.trim());
        const ppt = new pptxgen();

        ppt.layout = "LAYOUT_WIDE";
        ppt.author = "KryptAI";
        ppt.company = "KryptAI";
        ppt.subject = state.prompt;
        ppt.title = parsed.title;
        ppt.lang = "en-US";

        addCoverSlide(ppt, parsed.title, parsed.subtitle);
        parsed.slides.forEach((slide, index) => {
            const slideNumber = index + 1;
            if (slide.type === "stats") {
                addStatSlide(ppt, slideNumber, slide.title, slide.stats);
            }

            else if (slide.type === "conclusion") {
                addConclusionSlide(ppt, slide.title, slide.items);
            }

            else {
                addBulletSlide(ppt, slideNumber, slide.title, slide.items);
            }
        });

        const filename = `ppt-${Date.now()}.pptx`;
        const outputPath = path.join(process.cwd(), "public", "generated", filename);
        await ppt.writeFile({ fileName: outputPath });

        return {
            ...state,
            aiResponse: `# 📊 Presentation Generated

Your PowerPoint presentation has been created successfully.

## File

**${parsed.title}**

[📥 Download Presentation](${process.env.BACKEND_URL}/generated/${filename})
`,
        };

    } catch (error) {
        console.error("PPT Agent Error:", error);
        return { ...state, aiResponse: "❌ Failed to generate presentation." };

    }
};